### ISSUE TITLE
Deep link current url given the current state

### ISSUE THREAD

**Issue by elgalu** [TestLinkOpenSourceTRMS/testlink-code#6]
**As a** TestLink User
**I want to** send the current page state link by email/chat/whatever
**In order to** share what I'm seeing with others

Currently is not possible to share what a user is currently even after having some filters on:

- Test Project
- Current Test Plan
- etc..

Also happens in inner pages, some have unique links but seems to be hidden in iframes and doesn't propagate to the top page so always shows "/" or "/index.php?caller=login", hit refresh and your current state is gone.

Same thing goes with current Test Case and so on, fix is to have unique deep links that reflect the current state of the page the user is in.

**Comment by elgalu** [comment]
http://mantis.testlink.org/view.php?id=7028

**Comment by fmancardi** [comment]
Official issue tracker is mantis.
deleting here
